export const SET_AUTH_GARD = 'SET_AUTH_GARD'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE'

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAILURE = 'USER_SIGNIN_FAILURE'

export const SET_REDIRECT_LINK = 'SET_REDIRECT_LINK'
export const RESET_REDIRECT_LINK = 'RESET_REDIRECT_LINK'

export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAILURE = 'GET_REVIEWS_FAILURE'

export const GET_USER_CART_REQUEST = 'GET_USER_CART_REQUEST'
export const GET_USER_CART_SUCCESS = 'GET_USER_CART_SUCCESS'
export const GET_USER_CART_FAILURE = 'GET_USER_CART_FAILURE'

export const GET_COLORS_REQUEST = 'GET_COLORS_REQUEST'
export const GET_COLORS_SUCCESS = 'GET_COLORS_SUCCESS'
export const GET_COLORS_FAILURE = 'GET_COLORS_FAILURE'


export const GET_SIZES_REQUEST = 'GET_SIZES_REQUEST'
export const GET_SIZES_SUCCESS = 'GET_SIZES_SUCCESS'
export const GET_SIZES_FAILURE = 'GET_SIZES_FAILURE'

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE'

export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST'
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS'
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE'